Pin lower pandas version due to error when joining
The join operation in the columnify_json function raise a ValueError for
versions of pandas below 1.3. This commit fixes the dependency version to
avoid the problem.

The exception raised is:

ValueError: columns overlap but no suffix specified